tasks:
  - init: npm install
    command: | 
      npm install -g @aws-amplify/cli
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      rm awscliv2.zip
      sudo ./aws/install
      aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      aws configure set default.region ap-northeast-1